version: '3'

services:

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: CAMUNDA
      POSTGRES_PASSWORD: CAMUNDA

  camunda:
    image: camunda/camunda-bpm-platform
    container_name: camunda
    hostname: camunda
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres/CAMUNDA
      - DB_USERNAME=CAMUNDA
      - DB_PASSWORD=CAMUNDA
      - WAIT_FOR=postgres:5432
      - WAIT_FOR_TIMEOUT=60
    depends_on:
      - postgres