
info:
  app:
    name: recipe-elasticsearch
    description: elasticsearch
    version: 1.0.0-SNAPSHOT

management:
  info:
    build:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: info

spring:
  kafka:
    consumer:
      group-id: elastic-bulk
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      concurrency: 10
  elasticsearch:
    uris: http://localhost:9200