version: '3'

services:

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./compose/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./compose/mosquitto/data/:/mosquitto/data/
      - ./compose/mosquitto/logs/:/mosquitto/logs/