version: '3'

services:

  oracle:
    image: container-registry.oracle.com/database/free
    container_name: oracle
    hostname: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=FFllyywwaayy00!!
    profiles:
      - oracle

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: welcome1
    profiles:
      - postgres

  cloudbeaver:
    image: dbeaver/cloudbeaver
    container_name: cloudbeaver
    hostname: cloudbeaver
    ports:
      - "8080:8978"