version: "3"

services:

  collector:
    image: otel/opentelemetry-collector-contrib
    hostname: collector
    container_name: collector
    ports:
      - "5000:5000"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./compose/otel/config/config.yaml:/etc/otelcol-contrib/config.yaml
      - ./compose/otel/data/:/var/otel/data/

  data-prepper:
    image: opensearchproject/data-prepper
    hostname: data-prepper
    container_name: data-prepper
    ports:
      - "4900:4900"
    volumes:
      - ./compose/data-prepper/config/otel.yaml:/usr/share/data-prepper/pipelines/otel.yaml
    depends_on:
      - opensearch

  opensearch:
    image: opensearchproject/opensearch
    hostname: opensearch
    container_name: opensearch
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards
    hostname: opensearch-dashboards
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - opensearch
