receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  elasticsearch:
    endpoints: [http://elasticsearch:9200]
    logs_index: my_log_index
    sending_queue:
      enabled: true
      num_consumers: 20
      queue_size: 1000

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]