receivers:
  tcplog:
    listen_address: "0.0.0.0:5000"
    operators:
      - type: json_parser
        parse_from: body
        timestamp:
          parse_from: attributes.@timestamp
          layout: '%Y-%m-%dT%H:%M:%S.%s%j'

processors:
  batch:
  transform:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(body, attributes["message"])

exporters:
  elasticsearch:
    endpoints: [http://nginx:9200]
    logs_index: my_log_index
    sending_queue:
      enabled: true
      num_consumers: 20
      queue_size: 1000

service:
  pipelines:
    logs:
      receivers: [tcplog]
      processors: [transform,batch]
      exporters: [elasticsearch]