
server:
  port: 8080

info:
  app:
    name: person-service
    description: Person Service
    version: 1.0.0-SNAPSHOT

management:
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: person-service
  cloud:
    consul:
      discovery:
        enabled: true
        metadata:
          extra_values: '["Hello","World"]'
        prefer-ip-address: true
        tags: local,test,service
