version: '3'

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./compose/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml