
info:
  app:
    name: recipe-otel-sdk
    description: Recipe to test open telemetry and sdk logging
    version: 1.0.0-SNAPSHOT

management:
  info:
    build:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: info

