### Get connector plugins

GET http://localhost:8083/connector-plugins
Content-Type: application/json
Accept: application/json


### Get connectors

GET http://localhost:8083/connectors
Content-Type: application/json
Accept: application/json

### Get connector

GET http://localhost:8083/connectors/elasticsearch-connector
Content-Type: application/json
Accept: application/json

### Get connector status

GET http://localhost:8083/connectors/elasticsearch-connector/status
Content-Type: application/json
Accept: application/json

### Get connector tasks

GET http://localhost:8083/connectors/elasticsearch-connector/tasks
Content-Type: application/json
Accept: application/json

### Get connector info

GET http://localhost:8083/connectors/elasticsearch-connector/info
Content-Type: application/json
Accept: application/json

### Create connector

POST http://localhost:8083/connectors
Content-Type: application/json
Accept: application/json

{
  "name": "elasticsearch-connector",
  "config": {
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "transforms": "indexTransformation",
    "transforms.indexTransformation.type": "org.b8.kafka.connect.transforms.IndexTransformation",
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "connection.url": "http://elasticsearch:9200",
    "connection.compression": "false",
    "batch.size": "1",
    "flush.timeout.ms": "1000",
    "topics": "test-topic",
    "key.ignore": "true",
    "schema.ignore": "true",
    "type.name": "testtype"
  }
}

### Update connector

PUT http://localhost:8083/connectors/elasticsearch-connector/config
Content-Type: application/json

{
}

### Delete connector

DELETE http://localhost:8083/connectors/elasticsearch-connector
Content-Type: application/json