###

GET http://localhost:8080/actuator/mappings
Accept: application/json

###

GET http://localhost:8080/actuator/env
Accept: application/json

###

GET http://localhost:8080/actuator/configprops
Accept: application/json

###

GET http://localhost:8080/config-client/default/env(_)DEV
Accept: application/json

