management:
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

  endpoint:
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

debug: true

spring:
  application:
    name: config-client
  config:
    import: optional:configserver:http://config-server:8080

config-client:
  client-property: client-value